DjangoBookLibrary/book_store/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from books.views import Maplib
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),

    path('users/', include('users.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

DjangoBookLibrary/books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    BookDetailView,
    HomeListView,
    login_to_comment_redirect,
    rate_book_view,
    SearchBookListView,
    Maplib,
)


urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('search-book-results/', SearchBookListView, name='search'),
    path('book/<slug:slug>', BookDetailView.as_view(), name='bookDetail'),
    path('book/<slug:slug>/<rating>', rate_book_view, name='rate_book'),
    path('redirect-to-detail/<slug:slug>', login_to_comment_redirect,
         name='login_to_comment_redirect'),
    path('<slug:slug>/map_lib/', Maplib, name='map'),

]

DjangoBookLibrary/books/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class Book(models.Model):

    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=10000000, default="About book")
    image = models.ImageField(
        default='default_book.png', upload_to='books_pics')
    author = models.CharField(max_length=100)
    publish_date = models.DateField(blank=True, null=True, default='')
    last_rating = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    @property
    def actual_rating(self):
        list_of_stars = []
        for star in range(self.last_rating):
            list_of_stars.append(star)
        return list_of_stars

    @property
    def calc_rating(self):
        ratings = BookReview.objects.filter(book=self)
        if ratings:
            result = 0
            for rating in ratings:
                result += rating.rating
            result = int(result / len(ratings))
            return result
        else:
            return 0


class BookReview(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    rating = models.IntegerField()

    @property
    def actual_rating(self):
        list_of_stars = []
        for star in range(self.rating):
            list_of_stars.append(star)
        return list_of_stars


class BookComment(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.CharField(max_length=300)

    def __str__(self):
        return self.text

DjangoBookLibrary/books/forms.py
from django import forms


class CommentForm(forms.Form):
    text = forms.CharField(label='Add comment:', widget=forms.Textarea(
        attrs={'rows': 4, 'cols': 15}))

class CommentCreateForm(forms.Form):
    text = forms.CharField(label='Add comment:', widget=forms.Textarea(
        attrs={'rows': 4, 'cols': 15}))

class CommentUpdateForm(forms.Form):
    text = forms.CharField(label='Modify your comment:', widget=forms.Textarea(
        attrs={'rows': 4, 'cols': 15}))

DjangoBookLibrary/books/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.http import Http404, HttpResponseForbidden
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.views.generic.edit import FormMixin
from django.views.generic import (
    DetailView,
    FormView,
    ListView,
    TemplateView,
    UpdateView)

from .forms import (
    CommentForm,
    CommentCreateForm,
    CommentUpdateForm
)

from .models import (
    Book,
    BookComment,
    BookReview
)

# Create your views here.

class HomeListView(ListView):
    template_name = 'books/home.html'
    model = Book

    def get_queryset(self):
        queryset = super(HomeListView, self).get_queryset()
        return queryset.all().order_by('-last_rating')[:9]


def SearchBookListView(request):
    if request.method == 'POST':
        book_form = Book()
        book_form.id = int(request.POST['isbn'])
        book_form.image = request.POST['img']
        book_form.title = request.POST['title']
        book_form.slug = slugify(int(request.POST['isbn']))
        book_form.description = request.POST['contents']
        book_form.author = request.POST['author']
        book_form.publish_date = request.POST['publish_date']
        try:
            booklast = Book.objects.get(slug=book_form.slug).last_rating
            book_form.last_rating = booklast
        except:
            pass

        book_form.save()
        return redirect('bookDetail', slug=book_form.slug)
    else:
        pass
    return render(request, "books/book_search_result.html")


class BookDetailView(FormMixin, DetailView):
    model = Book
    form_class = CommentForm

    def get_success_url(self):
        return reverse('bookDetail', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['comments'] = BookComment.objects.filter(
            book=self.object).order_by('-id')
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        b = self.get_object()
        text = form.cleaned_data['text']
        try:
            new_comment = BookComment(
                text=text, book=b, user=self.request.user, id=self.request.POST['id'])
        except:
            new_comment = BookComment(
                text=text, book=b, user=self.request.user)
        new_comment.save()
        messages.success(self.request, "Your comment is added, thank you")
        return super().form_valid(form)


@login_required(login_url='login')
def login_to_comment_redirect(request, slug):
    return redirect('bookDetail', slug=slug)


def rate_book_view(request, slug, rating):
    try:
        b = Book.objects.get(slug=slug)
        if b and not(BookReview.objects.filter(user=request.user).filter(book=b)):
            review = BookReview(book=b, user=request.user, rating=rating)
            review.save()
            b.last_rating = b.calc_rating
            b.save()
            messages.success(
                request, 'You rated a book: ' + b.title)
        else:
            messages.warning(
                request, 'You already rated this book')
        return redirect('bookDetail', slug=b.slug)
    except Book.DoesNotExist:
        raise Http404("Book is unavailable")
    return redirect('bookDetail', slug=b.slug)


def Maplib(request, slug):
    context = {"slug" : slug}
    return render(request, 'maps/map_lib.html', context)

DjangoBookLibrary/books/templates/books/book_search_result.html
{% extends "base.html" %}
{% block content %}

<form class="searchForm" action="{% url 'search' %}" method=" GET">
    <div class="form-group row">
        <input class="form-control col-md-7" required="required" name="q" type="text" placeholder="Write title">
        <span class="col-md-1"></span>
        <button type="submit" class="btn btn-dark form-control col-md-2">Search</button>
    </div>
</form>

<h2>Search results for: "{{ request.GET.q }}":</h2>
<div class="row lastBooksContainer">

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://cdn.rawgit.com/mrk-j/paginga/v0.8.1/paginga.jquery.js"></script>
    <script type="text/javascript">
        var key = "{{request.GET.q}}"
        $.ajax({
            async: true,
            url: "https://dapi.kakao.com/v3/search/book?target=title",
            type: "GET",
            timeout: 3000,
            data: { query: key, size: 50 },
            dataType: "json",
            headers: { Authorization: "KakaoAK 975917afd98807b54fb0a8eb6009dbf9" },
            success: function (result) {
                $.each(result.documents, function (idx, item) {
                    var bookCard = $("<div></div").attr({ "class": "col-md-4 bookCard" })
                    var div = $("<div></div").attr({ "class": "cardBorder" })

                    var isbn = item.isbn.slice(-13)
                    isbn *= 1
                    var ISBNTd = $("<input></input>").attr({ name: "isbn", type: "hidden", value: isbn })

                    var image = item.thumbnail
                    if (image == "") {
                        var inputimg = $("<input></input>").attr({ type: "image", src: 'https://islandpress.org/sites/default/files/default_book_cover_2015.jpg', width: 120, hight: 174 })
                        var imgTd = $("<input></input>").attr({ name: "img", type: "hidden", value: 'https://islandpress.org/sites/default/files/default_book_cover_2015.jpg' })
                    }
                    else {
                        var inputimg = $("<input></input>").attr({ type: "image", src: item.thumbnail })
                        var imgTd = $("<input></input>").attr({ name: "img", type: "hidden", value: item.thumbnail })
                    }

                    var titleTd = $("<h5></h5>").text(item.title)
                    var inputtitle = $("<input></input>").attr({ name: "title", type: "hidden", value: item.title })

                    var authorTd = $("<h6></h6>").text(item.authors)
                    var inputauthor = $("<input></input>").attr({ name: "author", type: "hidden", value: item.authors })

                    var PbDtTd = $("<h6></h6>").text(item.datetime.substring(0, 10))
                    var inputPbDtTd = $("<input></input>").attr({ name: "publish_date", type: "hidden", value: item.datetime.substring(0, 10) })

                    var description = $("<h6></h6>").text(item.contents)
                    var inputdescription = $("<input></input>").attr({ name: "contents", type: "hidden", value: item.contents })


                    var form_method = $("<form></form>").attr({ method: "post" })

                    form_method.append('{% csrf_token %}')
                    form_method.append(inputtitle)
                    form_method.append(inputimg)
                    form_method.append(imgTd)
                    form_method.append(inputauthor)
                    form_method.append(inputPbDtTd)
                    form_method.append(inputdescription)
                    form_method.append(ISBNTd)

                    div.append(form_method)
                    div.append(titleTd)
                    div.append(authorTd)
                    div.append(PbDtTd)

                    bookCard.append(div)

                    $(".row:last").append(bookCard)
                    // $(".items").append(bookCard)

                })
            },
            error: function (request, status, error) {
                alert("code = " + request.status + " message = " + request.responseText + " error = " + error); // 실패 시 처리
                console.log(error)
            },
        })
        // $(".paginate").paginga({ itemsPerPage: 9 });
    </script>
</div>
</div>
{% endblock content %}

DjangoBookLibrary/books/templates/books/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1 class="display-4"> 책 Check!</h1>
    <p class="lead">Create your account and login to review, rate, and find books!</p>
    <hr class="my-4">
    <p>
        <h5>Search book</h5>
        <form class="searchForm" action="{% url 'search' %}" method=" GET">
            <div class="form-group row">
                <input class="form-control col-md-7" required="required" name="q" type="text" placeholder="Write title">
                <span class="col-md-1"></span>
                <button type="submit" class="btn btn-dark form-control col-md-2">Search</button>
            </div>
        </form>
    </p>
</div>


<hr class="my-4">
<h2>High Rated Books</h2>
<div class="row lastBooksContainer">
    {% for book in book_list %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder" , style="height: 100%;overflow:auto;">
            <div>
                <a href="{% url 'bookDetail' slug=book.slug %}"><img class="book_image" src="{{ book.image }}" alt="Book image"></a>
                <br><br>
                <h5>{{ book.title }}</h5>
                <h6>{{ book.author }}</h6>
                {% if book.actual_rating %}
                {% for rate in book.actual_rating %}
                <span class="fa fa-star checked"></span>
                {% endfor %} <br>
                {% else %}
                <h6>Nobody rated</h6>
                {% endif %}
            </div>

        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}